# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ContrastRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ContrastRank`, Hetx, PMat, narm, display_progress)
}

.ContrastValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ContrastValue`, Hetx, PMat, narm, display_progress)
}

.DissimilarityRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_DissimilarityRank`, Hetx, PMat, narm, display_progress)
}

.DissimilarityValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_DissimilarityValue`, Hetx, PMat, narm, display_progress)
}

.Entropy <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_Entropy`, Hetx, PMat, narm, display_progress)
}

.HomogeneityRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_HomogeneityRank`, Hetx, PMat, narm, display_progress)
}

.HomogeneityValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_HomogeneityValue`, Hetx, PMat, narm, display_progress)
}

.NormalizedEntropy <- function(Hetx, PMat, nrp, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_NormalizedEntropy`, Hetx, PMat, nrp, narm, display_progress)
}

.ProbabilityMatrixHorizontalDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixHorizontalDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal135Dynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal135Dynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixDiagonal45Dynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixDiagonal45Dynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixVerticalDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixVerticalDynamic`, vMat, d, narm, display_progress)
}

.ProbabilityMatrixAllDynamic <- function(vMat, d, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_ProbabilityMatrixAllDynamic`, vMat, d, narm, display_progress)
}

.WeightedEntropyAbsRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropyAbsRank`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropyAbsValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropyAbsValue`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropySqrRank <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropySqrRank`, Hetx, PMat, narm, display_progress)
}

.WeightedEntropySqrValue <- function(Hetx, PMat, narm, display_progress = TRUE) {
    .Call(`_StrucDiv_WeightedEntropySqrValue`, Hetx, PMat, narm, display_progress)
}

.focal_get <- function(d, dim, ngb) {
    .Call(`_StrucDiv_do_focal_get`, d, dim, ngb)
}

